adding migrations to CI

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -37,7 +37,6 @@ jobs:
       with:
         php-version: ${{ matrix.php-versions }}
         extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
-        tools: php-cs-fixer
       env:
         update: true
 
@@ -81,9 +80,12 @@ jobs:
     - name: Yarn build
       run: yarn run encore production
 
-    ## —— Code Style ✅ ———————————————————————————————————————————————————————————
-    - name: Run phpcsfixer
-      run: phpcsfixer fix --format=checkstyle
+    - name: Run Migration
+      run: |
+        php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+        php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+      env:
+        DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
     ## —— Tests ✅ ———————————————————————————————————————————————————————————
     - name: Run functionnal and unit tests
