ci fixing again

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -82,11 +82,16 @@ jobs:
 
     ## —— PHPStan ✅ ———————————————————————————————————————————————————————————
     - name: Run static analysis with PHPStan
+      env:
+        DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=mariadb-10.5.12
       run: ./vendor/bin/phpstan analyse -c phpstan.neon
 
     ## —— Doctrine 🐱 ————————————————————————————————————————————————————————————
     - name: Run Doctrine migrations and load fixtures
+      env:
+        DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=mariadb-10.5.12
       run: |
+        php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
         php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
         php bin/console doctrine:fixtures:load --append -n || echo "No fixtures found or fixtures load failed"
 
